/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.57
 * Generated at: 2026-08-25 20:01:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

jakarta.servlet.http.HttpSession s=request.getSession(false);
boolean logged=s!=null&&s.getAttribute("user_id")!=null;
String name=logged?(String)s.getAttribute("full_name"):"";
String email=logged?(String)s.getAttribute("email"):"";
if(name==null||name.trim().isEmpty())name="User";
if(email==null)email="";
String ctx=request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\r\n");
      out.write("<title>StayFinder | Find Your Perfect Stay</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("*{margin:0;padding:0;box-sizing:border-box}\r\n");
      out.write("html{scroll-behavior:smooth}\r\n");
      out.write("body{font-family:\"DM Sans\",Arial,sans-serif;color:#172033;background:#f5f7fa;overflow-x:hidden}\r\n");
      out.write("a{text-decoration:none}\r\n");
      out.write("\r\n");
      out.write(".navbar{position:absolute;top:0;left:0;width:100%;height:80px;padding:0 7%;display:flex;align-items:center;justify-content:space-between;z-index:100;color:white;border-bottom:1px solid rgba(255,255,255,.15)}\r\n");
      out.write(".logo{color:white;font-size:23px;font-weight:700}\r\n");
      out.write(".nav-links{display:flex;gap:25px;align-items:center}\r\n");
      out.write(".nav-links>a{color:white;font-size:14px}\r\n");
      out.write(".nav-links>a:hover{opacity:.8}\r\n");
      out.write("\r\n");
      out.write(".profile-wrapper{position:relative}\r\n");
      out.write(".profile-button{display:flex;align-items:center;gap:9px;padding:7px 13px 7px 7px;border:1px solid rgba(255,255,255,.45);border-radius:30px;color:white;cursor:pointer;background:rgba(255,255,255,.1)}\r\n");
      out.write(".profile-avatar{width:35px;height:35px;border-radius:50%;background:#f5c36a;color:#17324d;display:flex;align-items:center;justify-content:center;font-weight:700}\r\n");
      out.write(".profile-name{max-width:140px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:600}\r\n");
      out.write(".profile-menu{position:absolute;top:53px;right:0;width:260px;background:white;color:#172033;border-radius:14px;padding:18px;box-shadow:0 15px 40px rgba(0,0,0,.25);display:none}\r\n");
      out.write(".profile-menu.show{display:block}\r\n");
      out.write(".profile-header{padding-bottom:14px;border-bottom:1px solid #e5eaf0;margin-bottom:10px}\r\n");
      out.write(".profile-header strong{display:block;font-size:17px;color:#12355b;margin-bottom:5px}\r\n");
      out.write(".profile-header span{display:block;font-size:12px;color:#718096;word-break:break-all}\r\n");
      out.write(".profile-menu a{display:block;padding:11px 8px;color:#172033;border-radius:8px;font-size:14px}\r\n");
      out.write(".profile-menu a:hover{background:#f1f5f9}\r\n");
      out.write(".logout{color:#dc2626!important;border-top:1px solid #e5eaf0;margin-top:8px;padding-top:14px!important}\r\n");
      out.write("\r\n");
      out.write(".hero{min-height:760px;padding:150px 7% 90px;display:flex;align-items:center;background:linear-gradient(90deg,rgba(5,15,28,.93),rgba(5,15,28,.65),rgba(5,15,28,.35)),url(\"");
      out.print(ctx);
      out.write("/images/hotel-hero.jpg\");background-size:cover;background-position:center}\r\n");
      out.write(".hero-content{width:100%;max-width:1200px;margin:auto;color:white}\r\n");
      out.write(".badge{display:inline-block;padding:9px 17px;border-radius:30px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.25);margin-bottom:20px;font-size:13px}\r\n");
      out.write(".hero h1{max-width:800px;font-family:\"Playfair Display\",Georgia,serif;font-size:clamp(48px,6vw,78px);line-height:1.05;margin-bottom:20px}\r\n");
      out.write(".hero h1 span{color:#f5c36a}\r\n");
      out.write(".hero p{max-width:650px;color:#e3e8ef;font-size:17px;line-height:1.7;margin-bottom:38px}\r\n");
      out.write("\r\n");
      out.write(".search-container{width:100%;background:white;padding:10px;border-radius:18px;box-shadow:0 25px 70px rgba(0,0,0,.35)}\r\n");
      out.write(".search-box{display:grid;grid-template-columns:1.5fr 1fr 1fr 1.1fr 190px;gap:9px}\r\n");
      out.write(".field{min-height:75px;background:#f5f7fa;border:1px solid #e3e8ef;border-radius:12px;padding:12px 15px;display:flex;align-items:center;gap:10px}\r\n");
      out.write(".icon{font-size:21px}\r\n");
      out.write(".field-content{width:100%}\r\n");
      out.write(".field label{display:block;color:#718096;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:5px}\r\n");
      out.write(".field input,.field select{width:100%;border:0;outline:0;background:transparent;font:600 14px \"DM Sans\";color:#172033}\r\n");
      out.write(".guest-selects{display:flex;gap:5px}\r\n");
      out.write(".guest-selects select{min-width:0}\r\n");
      out.write(".search-button{min-height:75px;border:0;border-radius:12px;background:linear-gradient(135deg,#e19a28,#b96808);color:white;font:700 16px \"DM Sans\";cursor:pointer;padding:0 20px;transition:.25s}\r\n");
      out.write(".search-button:hover{transform:translateY(-3px);box-shadow:0 10px 25px rgba(185,104,8,.4)}\r\n");
      out.write("\r\n");
      out.write(".autocomplete{position:relative;width:100%}\r\n");
      out.write(".suggestions{position:absolute;left:0;right:0;top:52px;background:white;color:#172033;border-radius:10px;box-shadow:0 12px 30px rgba(0,0,0,.25);overflow:hidden;display:none;z-index:9999}\r\n");
      out.write(".suggestion{padding:11px 14px;border-bottom:1px solid #eee;cursor:pointer}\r\n");
      out.write(".suggestion:hover{background:#f1f5f9}\r\n");
      out.write(".suggestion strong{display:block;font-size:14px}\r\n");
      out.write(".suggestion small{color:#718096;font-size:12px}\r\n");
      out.write("\r\n");
      out.write(".trust{background:white;padding:25px 7%;border-bottom:1px solid #e5eaf0}\r\n");
      out.write(".trust-grid{max-width:1200px;margin:auto;display:grid;grid-template-columns:repeat(4,1fr);gap:20px}\r\n");
      out.write(".trust-item{text-align:center;color:#68778b;font-size:13px}\r\n");
      out.write(".trust-item strong{display:block;color:#172033;font-size:15px;margin-bottom:4px}\r\n");
      out.write("\r\n");
      out.write(".section{width:90%;max-width:1200px;margin:85px auto}\r\n");
      out.write(".section-title{text-align:center;margin-bottom:10px;font:700 40px \"Playfair Display\",Georgia,serif;color:#102a43}\r\n");
      out.write(".section-subtitle{text-align:center;color:#718096;margin-bottom:40px}\r\n");
      out.write("\r\n");
      out.write(".destinations{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}\r\n");
      out.write(".destination{height:280px;position:relative;overflow:hidden;border-radius:18px;background-size:cover;background-position:center;display:flex;align-items:flex-end;transition:.3s}\r\n");
      out.write(".destination:hover{transform:translateY(-7px);box-shadow:0 18px 35px rgba(0,0,0,.18)}\r\n");
      out.write(".destination:after{content:\"\";position:absolute;inset:0;background:linear-gradient(transparent 30%,rgba(0,0,0,.88))}\r\n");
      out.write(".destination-content{position:relative;z-index:2;color:white;padding:22px}\r\n");
      out.write(".destination h3{font:700 27px \"Playfair Display\",Georgia,serif;margin-bottom:5px}\r\n");
      out.write(".destination p{font-size:13px;color:#e5e7eb}\r\n");
      out.write("\r\n");
      out.write(".kolkata{background-image:url(\"");
      out.print(ctx);
      out.write("/images/kolkata.jpg\")}\r\n");
      out.write(".goa{background-image:url(\"");
      out.print(ctx);
      out.write("/images/goa.jpg\")}\r\n");
      out.write(".jaipur{background-image:url(\"");
      out.print(ctx);
      out.write("/images/jaipur.jpg\")}\r\n");
      out.write(".mumbai{background-image:url(\"");
      out.print(ctx);
      out.write("/images/mumbai.jpg\")}\r\n");
      out.write(".delhi{background-image:url(\"");
      out.print(ctx);
      out.write("/images/delhi.jpg\")}\r\n");
      out.write(".kerala{background-image:url(\"");
      out.print(ctx);
      out.write("/images/kerala.jpg\")}\r\n");
      out.write(".agra{background-image:url(\"");
      out.print(ctx);
      out.write("/images/agra.jpg\")}\r\n");
      out.write(".varanasi{background-image:url(\"");
      out.print(ctx);
      out.write("/images/varanasi.jpg\")}\r\n");
      out.write("\r\n");
      out.write(".features{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}\r\n");
      out.write(".feature{background:white;padding:28px 22px;border-radius:15px;border:1px solid #e5eaf0;text-align:center}\r\n");
      out.write(".feature-icon{font-size:30px;margin-bottom:15px}\r\n");
      out.write(".feature h3{color:#17324d;margin-bottom:8px}\r\n");
      out.write(".feature p{color:#718096;font-size:13px;line-height:1.6}\r\n");
      out.write("\r\n");
      out.write(".cta{width:90%;max-width:1200px;margin:0 auto 80px;padding:55px;border-radius:22px;background:linear-gradient(110deg,#071b30,#174a78);color:white;text-align:center}\r\n");
      out.write(".cta h2{font:700 36px \"Playfair Display\",Georgia,serif;margin-bottom:10px}\r\n");
      out.write(".cta p{color:#dce8f5;margin-bottom:22px}\r\n");
      out.write(".cta a{display:inline-block;padding:13px 25px;border-radius:9px;background:#f5c36a;color:#17324d;font-weight:700}\r\n");
      out.write("\r\n");
      out.write("footer{background:#071727;color:#9fb2c5;padding:35px 7%;text-align:center;font-size:13px}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:1050px){\r\n");
      out.write(".search-box{grid-template-columns:1fr 1fr}\r\n");
      out.write(".search-button{min-height:65px}\r\n");
      out.write(".destinations{grid-template-columns:1fr 1fr}\r\n");
      out.write(".features,.trust-grid{grid-template-columns:1fr 1fr}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width:650px){\r\n");
      out.write(".navbar{padding:0 5%}\r\n");
      out.write(".nav-links{gap:8px}\r\n");
      out.write(".nav-links>a{display:none}\r\n");
      out.write(".profile-name{display:none}\r\n");
      out.write(".profile-button{padding:5px}\r\n");
      out.write(".hero{padding:130px 5% 60px;min-height:900px}\r\n");
      out.write(".hero h1{font-size:48px}\r\n");
      out.write(".search-box,.destinations,.features,.trust-grid{grid-template-columns:1fr}\r\n");
      out.write(".guest-selects{display:grid;grid-template-columns:1fr 1fr}\r\n");
      out.write(".search-button{min-height:65px}\r\n");
      out.write(".section{margin:60px auto}\r\n");
      out.write(".cta{padding:40px 25px}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header class=\"navbar\">\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/index.jsp\" class=\"logo\">🏨 StayFinder</a>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"nav-links\">\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/index.jsp\">Home</a>\r\n");
      out.write("\r\n");
if(logged){
      out.write("\r\n");
      out.write("<div class=\"profile-wrapper\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"profile-button\" onclick=\"toggleProfile()\">\r\n");
      out.write("<div class=\"profile-avatar\">");
      out.print(name.substring(0,1).toUpperCase());
      out.write("</div>\r\n");
      out.write("<span class=\"profile-name\">");
      out.print(name);
      out.write("</span>\r\n");
      out.write("<span>▼</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"profile-menu\" id=\"profileMenu\">\r\n");
      out.write("<div class=\"profile-header\">\r\n");
      out.write("<strong>");
      out.print(name);
      out.write("</strong>\r\n");
      out.write("<span>");
      out.print(email);
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/myBookings\">📋 My Bookings</a>\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/index.jsp\">🏠 Home</a>\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/logout\" class=\"logout\">🚪 Logout</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}else{
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/login.html\">Login</a>\r\n");
      out.write("<a href=\"");
      out.print(ctx);
      out.write("/register.html\">Register</a>\r\n");
}
      out.write("\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section class=\"hero\" id=\"hero\">\r\n");
      out.write("<div class=\"hero-content\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"badge\">✦ Trusted stays across India</div>\r\n");
      out.write("\r\n");
if(logged){
      out.write("\r\n");
      out.write("<h1>Welcome,<br><span>");
      out.print(name);
      out.write("</span></h1>\r\n");
      out.write("<p>Welcome back to StayFinder. Find your next comfortable stay and manage your reservations easily.</p>\r\n");
}else{
      out.write("\r\n");
      out.write("<h1>Find Your <span>Perfect</span><br>Stay</h1>\r\n");
      out.write("<p>Discover beautiful hotels, comfortable rooms and memorable stays at destinations you'll love.</p>\r\n");
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"search-container\">\r\n");
      out.write("\r\n");
      out.write("<form class=\"search-box\" id=\"hotelSearchForm\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"field\">\r\n");
      out.write("<div class=\"icon\">📍</div>\r\n");
      out.write("<div class=\"field-content autocomplete\">\r\n");
      out.write("\r\n");
      out.write("<label>Destination</label>\r\n");
      out.write("\r\n");
      out.write("<input\r\n");
      out.write("id=\"location\"\r\n");
      out.write("name=\"location\"\r\n");
      out.write("type=\"text\"\r\n");
      out.write("placeholder=\"Where do you want to go?\"\r\n");
      out.write("autocomplete=\"off\"\r\n");
      out.write("required>\r\n");
      out.write("\r\n");
      out.write("<div class=\"suggestions\" id=\"suggestions\"></div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"field\">\r\n");
      out.write("<div class=\"icon\">📅</div>\r\n");
      out.write("<div class=\"field-content\">\r\n");
      out.write("<label>Check-in</label>\r\n");
      out.write("<input name=\"check_in\" id=\"checkIn\" type=\"date\" required>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"field\">\r\n");
      out.write("<div class=\"icon\">📅</div>\r\n");
      out.write("<div class=\"field-content\">\r\n");
      out.write("<label>Check-out</label>\r\n");
      out.write("<input name=\"check_out\" id=\"checkOut\" type=\"date\" required>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"field\">\r\n");
      out.write("<div class=\"icon\">👥</div>\r\n");
      out.write("<div class=\"field-content\">\r\n");
      out.write("\r\n");
      out.write("<label>Guests</label>\r\n");
      out.write("\r\n");
      out.write("<div class=\"guest-selects\">\r\n");
      out.write("\r\n");
      out.write("<select name=\"adults\">\r\n");
      out.write("<option value=\"1\">1 Adult</option>\r\n");
      out.write("<option value=\"2\" selected>2 Adults</option>\r\n");
      out.write("<option value=\"3\">3 Adults</option>\r\n");
      out.write("<option value=\"4\">4 Adults</option>\r\n");
      out.write("<option value=\"5\">5 Adults</option>\r\n");
      out.write("<option value=\"6\">6 Adults</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("<select name=\"children\">\r\n");
      out.write("<option value=\"0\" selected>0 Children</option>\r\n");
      out.write("<option value=\"1\">1 Child</option>\r\n");
      out.write("<option value=\"2\">2 Children</option>\r\n");
      out.write("<option value=\"3\">3 Children</option>\r\n");
      out.write("<option value=\"4\">4 Children</option>\r\n");
      out.write("<option value=\"5\">5 Children</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<button class=\"search-button\" type=\"submit\">Search Hotels →</button>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"trust\">\r\n");
      out.write("<div class=\"trust-grid\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"trust-item\">⭐<strong>4.8/5</strong>Average guest rating</div>\r\n");
      out.write("<div class=\"trust-item\">🏨<strong>50+ Properties</strong>Comfortable stays</div>\r\n");
      out.write("<div class=\"trust-item\">🔒<strong>Secure Booking</strong>Safe experience</div>\r\n");
      out.write("<div class=\"trust-item\">💬<strong>24/7 Support</strong>We're here to help</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"section-title\">Popular Destinations</h2>\r\n");
      out.write("<p class=\"section-subtitle\">Explore some of India's most loved cities and getaways.</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destinations\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination kolkata\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Kolkata</h3>\r\n");
      out.write("<p>The City of Joy • Culture & Heritage</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination goa\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Goa</h3>\r\n");
      out.write("<p>Beaches • Sunsets • Relaxation</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination jaipur\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Jaipur</h3>\r\n");
      out.write("<p>The Pink City • Royal Heritage</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination mumbai\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Mumbai</h3>\r\n");
      out.write("<p>City of Dreams • Coastal Life</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination delhi\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>New Delhi</h3>\r\n");
      out.write("<p>History • Monuments • Modern India</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination kerala\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Kerala</h3>\r\n");
      out.write("<p>Backwaters • Nature • Peace</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination agra\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Agra</h3>\r\n");
      out.write("<p>Taj Mahal • Mughal Heritage</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"destination varanasi\">\r\n");
      out.write("<div class=\"destination-content\">\r\n");
      out.write("<h3>Varanasi</h3>\r\n");
      out.write("<p>Ghats • Spirituality • Tradition</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("\r\n");
      out.write("<h2 class=\"section-title\">Why Choose StayFinder?</h2>\r\n");
      out.write("<p class=\"section-subtitle\">Everything you need for a comfortable hotel booking experience.</p>\r\n");
      out.write("\r\n");
      out.write("<div class=\"features\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"feature\">\r\n");
      out.write("<div class=\"feature-icon\">🏨</div>\r\n");
      out.write("<h3>Quality Hotels</h3>\r\n");
      out.write("<p>Find comfortable rooms for every type of traveller.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"feature\">\r\n");
      out.write("<div class=\"feature-icon\">💰</div>\r\n");
      out.write("<h3>Great Prices</h3>\r\n");
      out.write("<p>Discover stays at prices that fit your budget.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"feature\">\r\n");
      out.write("<div class=\"feature-icon\">🔐</div>\r\n");
      out.write("<h3>Secure Booking</h3>\r\n");
      out.write("<p>Your booking information stays protected.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"feature\">\r\n");
      out.write("<div class=\"feature-icon\">⭐</div>\r\n");
      out.write("<h3>Easy Experience</h3>\r\n");
      out.write("<p>Search, choose and book your room easily.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"cta\">\r\n");
      out.write("<h2>Ready for your next stay?</h2>\r\n");
      out.write("<p>Find your hotel and make your next trip memorable.</p>\r\n");
      out.write("<a href=\"#hero\">Start Searching →</a>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer>© 2026 StayFinder • Hotel Room Booking System</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function toggleProfile(){\r\n");
      out.write("const menu=document.getElementById(\"profileMenu\");\r\n");
      out.write("if(menu)menu.classList.toggle(\"show\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"click\",function(e){\r\n");
      out.write("const wrapper=document.querySelector(\".profile-wrapper\");\r\n");
      out.write("const menu=document.getElementById(\"profileMenu\");\r\n");
      out.write("\r\n");
      out.write("if(wrapper&&menu&&!wrapper.contains(e.target)){\r\n");
      out.write("menu.classList.remove(\"show\");\r\n");
      out.write("}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* DATE VALIDATION */\r\n");
      out.write("\r\n");
      out.write("const checkIn=document.getElementById(\"checkIn\");\r\n");
      out.write("const checkOut=document.getElementById(\"checkOut\");\r\n");
      out.write("\r\n");
      out.write("const today=new Date().toISOString().split(\"T\")[0];\r\n");
      out.write("\r\n");
      out.write("checkIn.min=today;\r\n");
      out.write("checkOut.min=today;\r\n");
      out.write("\r\n");
      out.write("checkIn.addEventListener(\"change\",function(){\r\n");
      out.write("\r\n");
      out.write("checkOut.min=checkIn.value;\r\n");
      out.write("\r\n");
      out.write("if(checkOut.value&&checkOut.value<=checkIn.value){\r\n");
      out.write("checkOut.value=\"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* CITY AUTOCOMPLETE */\r\n");
      out.write("\r\n");
      out.write("const locationInput=document.getElementById(\"location\");\r\n");
      out.write("const suggestions=document.getElementById(\"suggestions\");\r\n");
      out.write("\r\n");
      out.write("let cities=[];\r\n");
      out.write("\r\n");
      out.write("fetch(\"");
      out.print(ctx);
      out.write("/destinations\")\r\n");
      out.write(".then(function(response){\r\n");
      out.write("\r\n");
      out.write("if(!response.ok){\r\n");
      out.write("throw new Error(\"Destination servlet returned \"+response.status);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("return response.json();\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write(".then(function(data){\r\n");
      out.write("\r\n");
      out.write("if(Array.isArray(data)){\r\n");
      out.write("cities=data;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write(".catch(function(error){\r\n");
      out.write("\r\n");
      out.write("console.log(\"Could not load destinations:\",error);\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("locationInput.addEventListener(\"input\",function(){\r\n");
      out.write("\r\n");
      out.write("const typed=this.value.trim().toLowerCase();\r\n");
      out.write("\r\n");
      out.write("suggestions.innerHTML=\"\";\r\n");
      out.write("\r\n");
      out.write("if(typed.length===0){\r\n");
      out.write("\r\n");
      out.write("suggestions.style.display=\"none\";\r\n");
      out.write("return;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * Search the loaded city list.\r\n");
      out.write(" * Example:\r\n");
      out.write(" * KOL → Kolkata, West Bengal\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("const matches=cities.filter(function(city){\r\n");
      out.write("\r\n");
      out.write("return city.name &&\r\n");
      out.write("city.name.toLowerCase().startsWith(typed);\r\n");
      out.write("\r\n");
      out.write("}).slice(0,8);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(matches.length===0){\r\n");
      out.write("\r\n");
      out.write("suggestions.style.display=\"none\";\r\n");
      out.write("return;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("matches.forEach(function(city){\r\n");
      out.write("\r\n");
      out.write("const item=document.createElement(\"div\");\r\n");
      out.write("\r\n");
      out.write("item.className=\"suggestion\";\r\n");
      out.write("\r\n");
      out.write("const cityName=city.name || \"\";\r\n");
      out.write("const stateName=city.state || \"\";\r\n");
      out.write("\r\n");
      out.write("item.innerHTML=\r\n");
      out.write("\"<strong>📍 \"+cityName+\"</strong>\"+\r\n");
      out.write("\"<small>\"+stateName+\"</small>\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("item.addEventListener(\"click\",function(){\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * Display the full location to the user.\r\n");
      out.write(" */\r\n");
      out.write("locationInput.value=cityName+\", \"+stateName;\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * Store ONLY the city name for database search.\r\n");
      out.write(" */\r\n");
      out.write("locationInput.dataset.city=cityName;\r\n");
      out.write("\r\n");
      out.write("suggestions.style.display=\"none\";\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("suggestions.appendChild(item);\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("suggestions.style.display=\"block\";\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"click\",function(e){\r\n");
      out.write("\r\n");
      out.write("if(!e.target.closest(\".autocomplete\")){\r\n");
      out.write("\r\n");
      out.write("suggestions.style.display=\"none\";\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* HOTEL SEARCH */\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"hotelSearchForm\").addEventListener(\"submit\",function(e){\r\n");
      out.write("\r\n");
      out.write("e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("let location=locationInput.value.trim();\r\n");
      out.write("\r\n");
      out.write("const selectedCity=locationInput.dataset.city;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * If user selected a suggestion:\r\n");
      out.write(" *\r\n");
      out.write(" * Kolkata, West Bengal\r\n");
      out.write(" *\r\n");
      out.write(" * becomes:\r\n");
      out.write(" *\r\n");
      out.write(" * Kolkata\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("if(selectedCity){\r\n");
      out.write("\r\n");
      out.write("location=selectedCity;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * Also handle manually typed:\r\n");
      out.write(" *\r\n");
      out.write(" * Kolkata, West Bengal\r\n");
      out.write(" *\r\n");
      out.write(" * just in case.\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("else if(location.includes(\",\")){\r\n");
      out.write("\r\n");
      out.write("location=location.split(\",\")[0].trim();\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("const inDate=checkIn.value;\r\n");
      out.write("const outDate=checkOut.value;\r\n");
      out.write("\r\n");
      out.write("const adults=document.querySelector(\"[name='adults']\").value;\r\n");
      out.write("const children=document.querySelector(\"[name='children']\").value;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("if(!location){\r\n");
      out.write("\r\n");
      out.write("alert(\"Please enter a destination.\");\r\n");
      out.write("return;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if(!inDate){\r\n");
      out.write("\r\n");
      out.write("alert(\"Please select your check-in date.\");\r\n");
      out.write("return;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if(!outDate){\r\n");
      out.write("\r\n");
      out.write("alert(\"Please select your check-out date.\");\r\n");
      out.write("return;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if(outDate<=inDate){\r\n");
      out.write("\r\n");
      out.write("alert(\"Check-out must be after check-in.\");\r\n");
      out.write("return;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*\r\n");
      out.write(" * IMPORTANT:\r\n");
      out.write(" * Only the city is sent to the search servlet.\r\n");
      out.write(" *\r\n");
      out.write(" * Example:\r\n");
      out.write(" * Kolkata, West Bengal\r\n");
      out.write(" * ↓\r\n");
      out.write(" * location=Kolkata\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("window.location.href=\r\n");
      out.write("\"");
      out.print(ctx);
      out.write("/searchHotels\"+\r\n");
      out.write("\"?location=\"+encodeURIComponent(location)+\r\n");
      out.write("\"&check_in=\"+encodeURIComponent(inDate)+\r\n");
      out.write("\"&check_out=\"+encodeURIComponent(outDate)+\r\n");
      out.write("\"&adults=\"+encodeURIComponent(adults)+\r\n");
      out.write("\"&children=\"+encodeURIComponent(children);\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
